# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3cbdcaf4ce72d5015d404c520de51502"
name = "b2b-partial-pay"
application_url = "https://mco-b2b-partial-payment.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,write_orders,read_payment_mandate,write_payment_mandate,read_customers,write_customers"

[auth]
redirect_urls = [ "https://mco-b2b-partial-payment.onrender.com/api/auth" ]
